// Code generated by mkerrors.pl. DO NOT EDIT.

package errors

//go:generate perl mkerrors.pl
// InvalidReceiver
// InvalidArgument

type (
	InvalidReceiver string
	InvalidArgument string
)

var (
	ErrInvalidReceiver InvalidReceiver
	ErrInvalidArgument InvalidArgument
)

func (e *InvalidReceiver) Error() string {
	return "invalid receiver: + string(*e)"
}

func (e *InvalidArgument) Error() string {
	return "invalid argument: + string(*e)"
}

